kind: pipeline
type: exec
name: build

steps:
  - name: build
    commands:
      - docker-compose -p pycms build
      - docker-compose -p pycms push

---
name: test
type: docker
kind: pipeline
steps:
    - name: run db
      image: mongo
      detach: true

    - name: run_tests
      image: pycms_server
      commands:
        - bash ./test.sh
depends_on:
  - build