kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - docker-compose -p pycms build 
  - name: test
    commands:
      - docker-compose -p pycms up --build --abort-on-container-exit
  - name: run
    commands:
      - docker-compose -p pycms up -d


