kind: pipeline
type: exec
name: build

steps:
  - name: build
    commands:
      - docker-compose -p pycms build 

---
kind: pipeline
type: exec
name: test
steps:
  - name: test
    commands:
      - docker-compose -p pycms up --build --abort-on-container-exit

---
kind: pipeline
type: exec
name: run and push
steps:
  - name: push
    commands:
      - docker-compose -p pycms push
  - name: run
    commands:
      - docker-compose -p pycms down 
      - docker-compose -p pycms up -d


