kind: pipeline
type: exec
name: build

steps:
  - name: build
    commands:
      - docker-compose -p pycms build
      - docker-compose -p pycms push

---
kind: pipeline
type: docker
name: test

steps:
  - name: run db
    image: mongo

  - name: run_tests
    image: pycms_server
    commands:
      - bash ./test.sh
    depends_on:
      - "run db"