version: '3'
services:
        server:
                build: .
                ports:
                        - 8080:8080
                depends_on:
                        - db
                volumes:
                        - ./config.ini:/app/config.ini
        db:
                image: mongo
        tests:
                build: .
                command: bash ./test.sh
                depends_on:
                        - db
                        - server
