version: '3'
services:
        server:
                build: .
                ports:
                        - 8080:8080
                volumes:
                        - ./config.ini:/app/config.ini
                depends_on:
                        - db
        db:
                image: mongo
